- hosts: all
  remote_user: ec2-user
  become: true
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: installed
  - name: Remove Apache
    yum: 
      name: httpd
      state: removed