- hosts: web1
  remote_user: root
  become: true
  tasks:
    - name: Curl aws
      shell:
        cmd: curl http://169.254.169.254/latest/meta-data/public-ipv4
      register: curl
    - debug: var=curl.stdout_lines

#ansible-playbook -i aws.ini -vvvv service.yaml 
## don't need -v or -vvvv with lines after cmd included